#pragma once

#define DEPTH_WIDTH 512
#define DEPTH_HEIGHT 424
#define DEPTH_SIZE DEPTH_WIDTH * DEPTH_HEIGHT

#define COLOR_WIDTH 1920
#define COLOR_HEIGHT 1080

#define DEPTH_DEFAULT_SCALE 3.08
#define DEPTH_DEFAULT_OFFSET_X 160.0
#define DEPTH_DEFAULT_OFFSET_Y -112.0
